### ISSUE TITLE
Replace ChunkedDecoder with IterativeDecoder

### ISSUE THREAD

**Issue by thorwhalen** [otosense/recode#2]
See comparison here:

https://github.com/otosense/recode/wiki/Compare-performance-of-IterativeDecoder-and-ChunkedDecoder

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202893062686134/1203423850464249) by [Unito](https://www.unito.io)

**Comment by charlie-dufort** [comment]
Already done in [commit fb83289](https://github.com/otosense/recode/commit/fb83289c492c43eeaa65fe8f9b884e774b48bfa4)
