### ISSUE TITLE
Bug: encode_wav_header_bytes cannot set nframes

### ISSUE THREAD

**Issue by andeaseme** [otosense/recode#5]
Setting nframes with [encode_wav_header_bytes](https://github.com/otosense/recode/blob/master/recode/audio.py#LL173C5-L173C28) does not work.
A valid wav file cannot be made by joining the generated header with pcm bytes because nframes stays 0 in the header.

**Comment by charlie-dufort** [comment]
Duplicate of https://github.com/otosense/recode/issues/3
